[general]
import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
normal.family = "JetBrainsMono Nerd Font"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
